<a href="https://colab.research.google.com/github/zachfreitas/ADS_504_Machine_Learning/blob/main/Module_1/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 1.1 Exercises
Zachariah Freitas

In [ ]:
# Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Save this file here Module_1/Assignment_1.ipynb

## 1.1. Predicting Student Recommendation:
1.1.1. Download the student_records.csv file (located in your assignment prompt in Blackboard). <br>
1.1.2. Run all codes on the example in the lecture, Textbook 1 – Chapter 1: Page 19-28 and Page 55-64. The goal is to build a predictive model based on the dataset. The model can predict for any future student if they will be recommended for the grant based on their performance attributes. <br>
1.1.3. Write down your understanding about the codes and each part’s functioning.



### Mathematics
**Scalar**


In [ ]:
x=5
x

5

**Vector**

In [ ]:
# Create a vector/list.
x = [1,2,3,4,5]

# View the vector/list.
x

[1, 2, 3, 4, 5]

In [ ]:
# Import numpy library that has functions that help us work in matricies.
import numpy as np
# Create an vector/array
x = np.array([1,2,3,4,5])
# View the vector/array
print(x,'\n')
# View the datatype of x
print(type(x))

[1 2 3 4 5] 

<class 'numpy.ndarray'>


**Matrix**

In [ ]:
# Create a matrix
m = np.array([[1,5,2],
              [4,7,4],
              [2,0,9]])
# View the matrix
print(m)

[[1 5 2]
 [4 7 4]
 [2 0 9]]


In [ ]:
# View the matrix dimensions
print(m.shape)

(3, 3)


In [ ]:
# Matrix transpose
print('Matix Transpose:\n', m.transpose(), '\n')

Matix Transpose:
 [[1 4 2]
 [5 7 0]
 [2 4 9]] 



In [ ]:
# Matrix determinant
# If the determinant is zero then we cannot calculate an inverse, because it would be like dividing by zero or undefined.
print('Matix Determinant:\n', np.linalg.det(m), '\n')

Matix Determinant:
 -105.00000000000006 



In [ ]:
# Matrix inverse
# Why Do We Need an Inverse?
# Because with matrices we don't divide! Seriously, there is no concept of dividing by a matrix.
# But we can multiply by an inverse, which achieves the same thing.
m_inv = np.linalg.inv(m)
print('Matix Inverse:\n', m_inv, '\n')

Matix Inverse:
 [[-0.6         0.42857143 -0.05714286]
 [ 0.26666667 -0.04761905 -0.03809524]
 [ 0.13333333 -0.0952381   0.12380952]] 



In [ ]:
# Identity Matrix (result of matrix * matrix_inverse)
# Check your work.
iden_m = np.dot(m, m_inv)
iden_m = np.round(np.abs(iden_m),0)
print('Product of matrix and its inverse:\n', iden_m, '\n')

Product of matrix and its inverse:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



### Eigen Decomposition
Matrix decomposition technique.

In [ ]:
# Create Matrix Array
m = np.array([[1,5,2],
              [4,7,4],
              [2,0,9]])

# Do eigen decomposition
eigen_vals, eigen_vecs = np.linalg.eig(m)

# View the eigan values and eigan vectors
print('Eigan Values:\n', eigen_vals, '\n')
print('Eigan Vectors:\n', eigen_vecs, '\n')

Eigan Values:
 [-1.32455532 11.32455532  7.        ] 

Eigan Vectors:
 [[-0.91761521  0.46120352 -0.46829291]
 [ 0.35550789  0.79362022 -0.74926865]
 [ 0.17775394  0.39681011  0.46829291]] 



### Singular Value Decomposition (SVD)
Another matrix decomposistion technique.

$M_{m \times n} = U_{m \times m} S_{m \times n} V^T_{n \times n}$ <br>
Where: <br>
$ m = rows $ <br>
$ n = columns $

In [ ]:
# SVD
# Create Matrix Array
m = np.array([[1,5,2],
              [4,7,4],
              [2,0,9]])

# Do the SVD function
U, S, VT = np.linalg.svd(m)

# View the SVD outputs
print('Getting SVD outputs:\n')
print('U:\n',U,'\n')
print('S:\n',S,'\n')
print('VT:\n',VT,'\n')

Getting SVD outputs:

U:
 [[ 0.3831556  -0.39279153  0.83600634]
 [ 0.68811254 -0.48239977 -0.54202545]
 [ 0.61619228  0.78294653  0.0854506 ]] 

S:
 [12.10668383  6.91783499  1.25370079] 

VT:
 [[ 0.36079164  0.55610321  0.74871798]
 [-0.10935467 -0.7720271   0.62611158]
 [-0.92621323  0.30777163  0.21772844]] 



### Statistics

In [ ]:
# Descriptive Statistics
import scipy as sp
import numpy as np
from scipy import stats


# Get the data
nums = np.random.randint(1,20, size=(1,15))[0]
print('Data: ', nums)

Data:  [ 7  2 10  4  7  6 14  6  9  6  3  6  9 10 19]


In [ ]:
# get descriptive stats
print('Mean:', np.mean(nums))
print('Median:', np.median(nums))
print('Mode:', float(stats.mode(nums)[0]))
print('Standard Deviation:', np.std(nums))
print('Variance:', np.var(nums))
print('Skew:', sp.stats.skew(nums))
print('Kurtosis:', sp.stats.kurtosis(nums))


Mean: 7.866666666666666
Median: 7.0
Mode: 6.0
Standard Deviation: 4.177186719418811
Variance: 17.448888888888884
Skew: 1.1256917160228568
Kurtosis: 1.1258261277339399


### Natural Language Processing (NLP)

In [ ]:
from nltk.parse.stanford import StanfordParser

sentence = 'The quick brown fox jumps over the lazy dog'

In [ ]:
#from nltk.parse import CoreNLPParser
#parser = CoreNLPParser()
#parser.parse_sents(...)
#parser.raw_parse(...)
#parser.raw_parse_sents(...)
#*deprecated*
# *deprecated*
# parser.parse_text()

In [ ]:
from nltk.parse import CoreNLPParser
scp = CoreNLPParser(path_to_jar='E:/stanford/standford-parser-full-2015-04-20/standford-parser.jar', path_to_models_jar='E:/stanford/standford-parser-full-2015-04-20/standford-parser-3.5.2-models.jar')

TypeError: ignored

In [ ]:
# Create parser object
#scp = StanfordParser(path_to_jar='E:/stanford/standford-parser-full-2015-04-20/standford-parser.jar', 
#                      path_to_models_jar='E:/stanford/standford-parser-full-2015-04-20/standford-parser-3.5.2-models.jar')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: The StanfordParser will be deprecated
Please use nltk.parse.corenlp.CoreNLPParser instead.
  This is separate from the ipykernel package so we can avoid doing imports until


LookupError: ignored

### Real-World Case Study: Predicting Student Grant Recomendations
**Data Retrieval**

In [ ]:
# Copy of data in my github for perputuity. 
import pandas as pd
# Turn off warning messages
pd.options.mode.chained_assignment = None # default = 'warn'

# Get data
sr_df = pd.read_csv('https://github.com/zachfreitas/ADS_504_Machine_Learning/raw/main/Module_1/student_records.csv')
sr_df

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

**Data Preparation** <br>
**Feature Extraction and Engineering**

In [ ]:
# Get Features and corresponding outcomes
feature_names = ['OverallGrade', 'Obedient', 'ResearchScore', 'ProjectScore']
training_features = sr_df[feature_names]
outcome_name = ['Recommend']
outcome_labels = sr_df[outcome_name]

# View features
training_features

# Normally I would create a test train split using the following code but this example dosn't require it.
# from sklearn.model_selection import train_test_split
# x_train,x_test,y_train,y_test=train_test_split(training_features,outcome_labels,test_size=0.2)


OverallGrade Obedient  ResearchScore  ProjectScore
0            A        Y             90            85
1            C        N             85            51
2            F        N             10            17
3            B        Y             75            71
4            E        N             20            30
5            A        Y             92            79
6            B        Y             60            59
7            C        Y             75            33

In [ ]:
# View outcome labels
outcome_labels

Recommend
0       Yes
1       Yes
2        No
3        No
4        No
5       Yes
6        No
7        No

In [ ]:
# List down features based on type
numeric_feature_names = [ 'ResearchScore', 'ProjectScore']
categorical_feature_names = ['OverallGrade', 'Obedient']

In [ ]:
from sklearn.preprocessing  import StandardScaler
ss = StandardScaler()

# fit scaler on numeric features
ss.fit(training_features[numeric_feature_names])

# scale numeric fearures now
training_features[numeric_feature_names] = ss.transform(training_features[numeric_feature_names])

# View updated featureset
training_features


OverallGrade Obedient  ResearchScore  ProjectScore
0            A        Y       0.899583      1.376650
1            C        N       0.730648     -0.091777
2            F        N      -1.803390     -1.560203
3            B        Y       0.392776      0.772004
4            E        N      -1.465519     -0.998746
5            A        Y       0.967158      1.117516
6            B        Y      -0.114032      0.253735
7            C        Y       0.392776     -0.869179

In [ ]:
# Create dummy variables from categorical features.
training_features = pd.get_dummies(training_features, columns = categorical_feature_names)

# View newly engineered features.
training_features

ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_B  \
0       0.899583      1.376650               1               0   
1       0.730648     -0.091777               0               0   
2      -1.803390     -1.560203               0               0   
3       0.392776      0.772004               0               1   
4      -1.465519     -0.998746               0               0   
5       0.967158      1.117516               1               0   
6      -0.114032      0.253735               0               1   
7       0.392776     -0.869179               0               0   

   OverallGrade_C  OverallGrade_E  OverallGrade_F  Obedient_N  Obedient_Y  
0               0               0               0           0           1  
1               1               0               0           1           0  
2               0               0               1           1           0  
3               0               0               0           0           1  
4               0               1               0           1           0  
5               0               0               0           0           1  
6               0               0               0           0           1  
7               1               0               0           0           1

In [ ]:
# Get a list of newly created categorical fearures
categorical_engineered_features = list(set(training_features.columns) - set(numeric_feature_names))
# View new category feature column names
categorical_engineered_features

['OverallGrade_A',
 'OverallGrade_C',
 'Obedient_Y',
 'OverallGrade_F',
 'OverallGrade_E',
 'OverallGrade_B',
 'Obedient_N']

**Modeling**

In [ ]:
from sklearn.linear_model import LogisticRegression
import numpy as np

#fit the model
lr = LogisticRegression()


model = lr.fit(training_features, np.array(outcome_labels['Recommend']))

# View the parameters
model.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 100,
 'multi_class': 'auto',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

**Model Evaluation**

In [ ]:
 # simple evaluation on training data
pred_labels = model.predict(training_features)
actual_labels = np.array(outcome_labels['Recommend'])

# evaluate model performance
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

print('Accuracy:', float(accuracy_score(actual_labels, pred_labels))*100, '%')
print('Classification Stats:')
print(classification_report(actual_labels, pred_labels))

Accuracy: 100.0 %
Classification Stats:
              precision    recall  f1-score   support

          No       1.00      1.00      1.00         5
         Yes       1.00      1.00      1.00         3

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8



**Model Deployment**

In [ ]:
# from sklearn.externals import joblib
import joblib
import os

# save models to be deployed on your server
if not os.path.exists('/content/drive/MyDrive/Colab Notebooks/Model'):
  os.mkdir('/content/drive/MyDrive/Colab Notebooks/Model')
if not os.path.exists('/content/drive/MyDrive/Colab Notebooks/Scaler'):
  os.mkdir('/content/drive/MyDrive/Colab Notebooks/Scaler') 

# Create a pickle file
# Pickling is a process of converting a Python object into a byte stream to store it in a file/database, maintain program state across sessions, or transport data over the network.
joblib.dump(model, r'/content/drive/MyDrive/Colab Notebooks/Model/model.pickle') 
joblib.dump(ss, r'/content/drive/MyDrive/Colab Notebooks/Scaler/scaler.pickle')

['/content/drive/MyDrive/Colab Notebooks/Scaler/scaler.pickle']

**Prediction in Action**

In [ ]:
# load model and scaler objects
model = joblib.load(r'/content/drive/MyDrive/Colab Notebooks/Model/model.pickle')
scaler = joblib.load(r'/content/drive/MyDrive/Colab Notebooks/Scaler/scaler.pickle')

In [ ]:
## data retrieval
new_data = pd.DataFrame([{'Name': 'Nathan', 'OverallGrade': 'F', 
                          'Obedient': 'N', 'ResearchScore': 30, 'ProjectScore': 20},
                          {'Name': 'Thomas', 'OverallGrade': 'A',
                           'Obedient': 'Y', 'ResearchScore': 78, 'ProjectScore': 80}])
 
new_data = new_data[['Name', 'OverallGrade', 'Obedient', 'ResearchScore', 'ProjectScore']]
 
new_data

Name OverallGrade Obedient  ResearchScore  ProjectScore
0  Nathan            F        N             30            20
1  Thomas            A        Y             78            80

In [ ]:
## Since we don't have new data I'm just going to use our original data set for simplication of this task.
# in the future I would use a test set or have a truely new dataset.
new_data = sr_df
## New data preparation
prediction_features = new_data[feature_names]

# scaling
prediction_features[numeric_feature_names] = scaler.transform(prediction_features[numeric_feature_names])

# engineering categorical variables
prediction_features = pd.get_dummies(prediction_features, columns=categorical_feature_names)
 
# view feature set
prediction_features

ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_B  \
0       0.899583      1.376650               1               0   
1       0.730648     -0.091777               0               0   
2      -1.803390     -1.560203               0               0   
3       0.392776      0.772004               0               1   
4      -1.465519     -0.998746               0               0   
5       0.967158      1.117516               1               0   
6      -0.114032      0.253735               0               1   
7       0.392776     -0.869179               0               0   

   OverallGrade_C  OverallGrade_E  OverallGrade_F  Obedient_N  Obedient_Y  
0               0               0               0           0           1  
1               1               0               0           1           0  
2               0               0               1           1           0  
3               0               0               0           0           1  
4               0               1               0           1           0  
5               0               0               0           0           1  
6               0               0               0           0           1  
7               1               0               0           0           1

In [ ]:
# add missing categorical feature columns
current_categorical_engineered_features = set(prediction_features.columns) - set(numeric_feature_names)
missing_features = set(categorical_engineered_features) - current_categorical_engineered_features
for feature in missing_features:
  # add zeros since feature is absent in these data samples
  prediction_features[feature] = [0] * len(prediction_features) 

# view final feature set
prediction_features

ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_B  \
0       0.899583      1.376650               1               0   
1       0.730648     -0.091777               0               0   
2      -1.803390     -1.560203               0               0   
3       0.392776      0.772004               0               1   
4      -1.465519     -0.998746               0               0   
5       0.967158      1.117516               1               0   
6      -0.114032      0.253735               0               1   
7       0.392776     -0.869179               0               0   

   OverallGrade_C  OverallGrade_E  OverallGrade_F  Obedient_N  Obedient_Y  
0               0               0               0           0           1  
1               1               0               0           1           0  
2               0               0               1           1           0  
3               0               0               0           0           1  
4               0               1               0           1           0  
5               0               0               0           0           1  
6               0               0               0           0           1  
7               1               0               0           0           1

In [ ]:
## predict using model
predictions = model.predict(prediction_features)
  
## display results
new_data['Recommend'] = predictions

new_data


Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [ ]:
training_features

ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_B  \
0       0.899583      1.376650               1               0   
1       0.730648     -0.091777               0               0   
2      -1.803390     -1.560203               0               0   
3       0.392776      0.772004               0               1   
4      -1.465519     -0.998746               0               0   
5       0.967158      1.117516               1               0   
6      -0.114032      0.253735               0               1   
7       0.392776     -0.869179               0               0   

   OverallGrade_C  OverallGrade_E  OverallGrade_F  Obedient_N  Obedient_Y  
0               0               0               0           0           1  
1               1               0               0           1           0  
2               0               0               1           1           0  
3               0               0               0           0           1  
4               0               1               0           1           0  
5               0               0               0           0           1  
6               0               0               0           0           1  
7               1               0               0           0           1

In [ ]:
sr_df.columns

Index(['Name', 'OverallGrade', 'Obedient', 'ResearchScore', 'ProjectScore',
       'Recommend'],
      dtype='object')

In [ ]:
dim(sr_df)

NameError: ignored

In [ ]:
sr_df.shape

(8, 6)

In [ ]:
sr_df

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [ ]:
sr_df.columns

In [ ]:
sr_df.head()

In [ ]:
ProjectScore = sns.boxplot(x="ProjectScore", y="Recommend", data = sr_df, orient = 'horizontal')
plt.show()

In [ ]:
ResearchScore = sns.boxplot(x="ResearchScore", y="Recommend", data = sr_df, orient = 'horizontal')
plt.show()

In [ ]:
g = sns.catplot(x="ProjectScore", y="OverallGrade",
                hue="Recommend", col="Obedient",
                data=sr_df, kind="box",
                height=4, aspect=.7);

In [ ]:
g = sns.catplot(x="ResearchScore", y="OverallGrade",
                hue="Recommend", col="Obedient",
                data=sr_df, kind="box",
                height=4, aspect=.7);

## 1.2. Introducing the Python Machine Learning Ecosystem:
1.2.1. Download the simplemaps-worldcities-basic.csv file (located in your assignment prompt in Blackboard). <br>
1.2.2. Run all codes on the example in the lecture, Textbook 1 – Chapter 2: Page 75-112. The goal is to build a predictive model based on the dataset. The model can predict for any future student if they will be recommended for the grant based on their performance attributes. <br>
1.2.3. Write down your understanding about the codes and each part’s functioning. <br>


### Numpy ndarray

In [5]:
import numpy as np
arr = np.array([1,3,4,5,6])
print('View the Array:', '\n', arr,'\n')
print('Array Dimensions:', arr.shape,'\n') 
print('Data Type:', arr.dtype)

View the Array: [1 3 4 5 6] 

Array Dimensions: (5,) 

Data Type: int64


In [12]:
arr = np.array([1,'st','er',3])
print('Data Type:', arr.dtype)

Data Type: <U21


In [13]:
# This mixed array type can't be summed.  Here is the error.
np.sum(arr)

TypeError: ignored

#### Creating Arrays

In [14]:
arr = np.array([[1,2,3],[2,4,6],[8,8,8]])
print('View the Array:', '\n', arr,'\n')
print('Array Dimensions:', arr.shape,'\n') 
print('Data Type:', arr.dtype)

View the Array: 
 [[1 2 3]
 [2 4 6]
 [8 8 8]] 

Array Dimensions: (3, 3) 

Data Type: int64


In [15]:
# np.zeros: Creates a matrix of specified dimensions containing only zeroes:
arr = np.zeros((2,4))
print('View the Array:', '\n', arr,'\n')
print('Array Dimensions:', arr.shape,'\n') 
print('Data Type:', arr.dtype)

View the Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

Array Dimensions: (2, 4) 

Data Type: float64


In [18]:
# np.ones: Creates a matrix of specified dimension containing only ones:
arr = np.ones((2,4))
print('View the Array:', '\n', arr,'\n')
print('Array Dimensions:', arr.shape,'\n') 
print('Data Type:', arr.dtype)

View the Array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

Array Dimensions: (2, 4) 

Data Type: float64


In [19]:
# np.identity: Creates an identity matrix of specified dimensions
arr = np.identity(3)
print('View the Array:', '\n', arr,'\n')
print('Array Dimensions:', arr.shape,'\n') 
print('Data Type:', arr.dtype)

View the Array: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Array Dimensions: (3, 3) 

Data Type: float64


In [31]:
# np.identity:  Create an array of a specified dimension with random values. 
arr = np.random.randn(3,4)
print('View the Array:', '\n', arr,'\n')
print('Array Dimensions:', arr.shape,'\n') 
print('Data Type:', arr.dtype)

View the Array: 
 [[ 1.5496471   1.93373107  1.26561416  1.22632726]
 [ 0.54064373  2.49116164  0.23216267 -0.30033888]
 [ 0.39832141 -0.50116865  0.29645972 -0.22944835]] 

Array Dimensions: (3, 4) 

Data Type: float64


In [76]:
# Create an array of nan values.
arr = np.empty((3,3))
arr[:] = np.nan # or I could use: arr.fill(np.nan)
print('View the Array:', '\n', arr,'\n')
print('Array Dimensions:', arr.shape,'\n') 
print('Data Type:', arr.dtype)

View the Array: 
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]] 

Array Dimensions: (3, 3) 

Data Type: float64


In [34]:
# genfromtxt:  Create an array from delimited text. There are better ways to import data.
import io
b = io.BytesIO(b"2,23,33\n32,42,63.4\n35,77,12")
arr = np.genfromtxt(b, delimiter=",")
print('View the Array:', '\n', arr,'\n')
print('Array Dimensions:', arr.shape,'\n') 
print('Data Type:', arr.dtype)

View the Array: 
 [[ 2.  23.  33. ]
 [32.  42.  63.4]
 [35.  77.  12. ]] 

Array Dimensions: (3, 3) 

Data Type: float64


#### Accessing Array Elements

#### Basic Indexing and Slicing

In [35]:
# Grab the second row of a two dimensional array.
arr[1]

array([32. , 42. , 63.4])

In [37]:
# Create a three dimensional array
arr = np.arange(12).reshape(2,2,3)
print('View the Array:', '\n', arr,'\n')
print('Array Dimensions:', arr.shape,'\n') 
print('Data Type:', arr.dtype)

View the Array: 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] 

Array Dimensions: (2, 2, 3) 

Data Type: int64


In [38]:
# We get the first dimension of the 3 dimensional array.
arr[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [39]:
# Create a one dimensional array with 10 values ranging from 0 to 9.
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# Slice the array to get the last 5 values.
arr[5:]

array([5, 6, 7, 8, 9])

In [41]:
# Slice the array to get values 5 thru 7,
arr[5:8]

array([5, 6, 7])

In [42]:
# Slice the array to get the first 5 values
arr[:-5]

array([0, 1, 2, 3, 4])

In [43]:
# Create a three dimensional array with 12 values ranging from 0 to 11.
arr = np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [44]:
# Slice the array to get the second and third dimension
arr[1:2]

array([[[ 6,  7,  8],
        [ 9, 10, 11]]])

In [46]:
arr = np.arange(27).reshape(3,3,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [47]:
# Slice the array to get the third column. Version 1
arr[:,:,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [49]:
# Slice the array to get the third column. Version 2
arr[...,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

#### Advanced Indexing <br>
**Integer array indexing:**

In [51]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
# Indexing an array with multiple coordinate pairs [[Rows/Dimension One],[Columns/Dimension Two]]
arr[[0,1,2],[1,0,0]]

array([1, 3, 6])

**Boolean indexing:**

In [54]:
# Create an array of names and random numbers
cities = np.array(["delhi","bangalore","mumbai","chennai","bhopal"])
city_data = np.random.randn(5,3)
city_data

array([[-1.00200729, -0.83798934,  0.91500136],
       [ 0.12343831, -0.42139258,  0.76431171],
       [-0.50553394, -2.04949165,  0.72401862],
       [-1.43423503, -1.54905791,  0.08963096],
       [-0.71631715,  0.41314868,  0.8191367 ]])

In [57]:
# Get the random array values with the same integer placement as "delhi" in the cities array.
city_data[cities =="delhi"]

array([[-1.00200729, -0.83798934,  0.91500136]])

In [59]:
# Select the greater than zero elements of an array.
city_data[city_data > 0]

array([0.91500136, 0.12343831, 0.76431171, 0.72401862, 0.08963096,
       0.41314868, 0.8191367 ])

In [61]:
# Now let replace the values above with zero. Now the matrix should only have values that are zero or less.
city_data[city_data >0] = 0
city_data

array([[-1.00200729, -0.83798934,  0.        ],
       [ 0.        , -0.42139258,  0.        ],
       [-0.50553394, -2.04949165,  0.        ],
       [-1.43423503, -1.54905791,  0.        ],
       [-0.71631715,  0.        ,  0.        ]])

#### Operations on Arrays

In [62]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
# add 5 to every element in the array
arr + 5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [64]:
# Multiply every element in the array by 2.
arr * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [67]:
# Add two arrays together element-wise. Repeatedly adds on non shared dimensions. This is known as broadcasting.
arr1 = np.arange(15).reshape(5,3)
arr2 = np.arange(5).reshape(5,1)
print('Results of arr2 + arr1:','\n',arr2 + arr1,'\n')
print('arr1:','\n',arr1,'\n')
print('arr2:','\n',arr2,'\n')

Results of arr2 + arr1: 
 [[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]] 

arr1: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

arr2: 
 [[0]
 [1]
 [2]
 [3]
 [4]] 



In [68]:
# Create a 5 by 3 array.
arr1 = np.random.randn(5,3)
arr1

array([[ 1.21244622, -0.9409891 , -0.47484524],
       [ 0.15157656, -0.25166554,  0.13602481],
       [ 0.54408891, -0.46910495, -0.76098339],
       [ 0.20067257, -0.36137076,  0.58253445],
       [ 0.73363561, -1.42311552,  1.08008672]])

In [73]:
# The function modf will return the fractional and the integer part of the input supplied to it. Output is two seperate arrays.
np.modf(arr1)

(array([[ 0.21244622, -0.9409891 , -0.47484524],
        [ 0.15157656, -0.25166554,  0.13602481],
        [ 0.54408891, -0.46910495, -0.76098339],
        [ 0.20067257, -0.36137076,  0.58253445],
        [ 0.73363561, -0.42311552,  0.08008672]]), array([[ 1., -0., -0.],
        [ 0., -0.,  0.],
        [ 0., -0., -0.],
        [ 0., -0.,  0.],
        [ 0., -1.,  1.]]))

#### Linear Algebra Using numpy

In [ ]:
# Copy of data in my github for perputuity. 
wc_df = pd.read_csv('https://github.com/zachfreitas/ADS_504_Machine_Learning/raw/main/Module_1/simplemaps-worldcities-basic.csv')

In [ ]:
***Accessing Array Elements***

## 1.3. Recommending Movies:
1.3.1. Load the MovieLens dataset from Tensorflow Datasets (movielens/100k_ratings and movielens/100k_movies). <br>
1.3.2. Follow the same steps in 1.2 and build a prediction model. <br>


In [ ]:
import tensorflow_datasets as tfds

In [ ]:
tfds.list_builders()

In [ ]:
# https://colab.research.google.com/github/tensorflow/datasets/blob/master/docs/overview.ipynb

ds = tfds.load('movielens/100k-ratings', split='train')
ds = ds.take(1)

for image, label in tfds.as_numpy(ds):
  print(type(image), type(label), label)

In [ ]:
# Load the MovieLens 100K data.
ratings = tfds.load(
    "movielens/100k-ratings",
    split="train"
)

# Get the ratings data.
ratings = (ratings
           # Retain only the fields we need.
           .map(lambda x: {"user_id": x["user_id"], "movie_title": x["movie_title"]})
           # Cache for efficiency.
           .cache(tempfile.NamedTemporaryFile().name)
)

# Get the movies data.
movies = tfds.load("movielens/100k-movies", split="train")
movies = (movies
          # Retain only the fields we need.
          .map(lambda x: x["movie_title"])
          # Cache for efficiency.
          .cache(tempfile.NamedTemporaryFile().name))

In [ ]:
movies

In [ ]:
x = tfds.as_dataframe(movies)
x.head()

In [ ]:
y = tfds.as_dataframe(ratings)
y.head()

In [ ]:
import os
import pandas as pd
from mxnet import gluon, np
from d2l import mxnet as d2l

In [ ]:
#@save
d2l.DATA_HUB['ml-100k'] = (
    'https://files.grouplens.org/datasets/movielens/ml-100k.zip',
    'cd4dcac4241c8a4ad7badc7ca635da8a69dddb83')

#@save
def read_data_ml100k():
    data_dir = d2l.download_extract('ml-100k')
    names = ['user_id', 'item_id', 'rating', 'timestamp']
    data = pd.read_csv(os.path.join(data_dir, 'u.data'), '\t', names=names,
                       engine='python')
    num_users = data.user_id.unique().shape[0]
    num_items = data.item_id.unique().shape[0]
    return data, num_users, num_items

In [ ]:
data, num_users, num_items = read_data_ml100k()
sparsity = 1 - len(data) / (num_users * num_items)
print(f'number of users: {num_users}, number of items: {num_items}')
print(f'matrix sparsity: {sparsity:f}')
print(data.head(5))

In [ ]:
!pip install -q tensorflow-recommenders
!pip install -q --upgrade tensorflow-datasets

In [ ]:
import os
import pprint
import tempfile

from typing import Dict, Text

import numpy as np
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_recommenders as tfrs

In [ ]:
"movielens/100k_movies"

In [ ]:
ratings = tfds.load("movielens/100k-ratings", split="train")

ratings = ratings.map(lambda x: {
    "movie_title": x["movie_title"],
    "user_id": x["user_id"],
    "user_rating": x["user_rating"]
})

In [ ]:
tf.random.set_seed(42)
shuffled = ratings.shuffle(100_000, seed=42, reshuffle_each_iteration=False)

train = shuffled.take(80_000)
test = shuffled.skip(80_000).take(20_000)

In [ ]:
movie_titles = ratings.batch(1_000_000).map(lambda x: x["movie_title"])
user_ids = ratings.batch(1_000_000).map(lambda x: x["user_id"])

unique_movie_titles = np.unique(np.concatenate(list(movie_titles)))
unique_user_ids = np.unique(np.concatenate(list(user_ids)))

In [ ]:
class RankingModel(tf.keras.Model):

  def __init__(self):
    super().__init__()
    embedding_dimension = 32

    # Compute embeddings for users.
    self.user_embeddings = tf.keras.Sequential([
      tf.keras.layers.StringLookup(
        vocabulary=unique_user_ids, mask_token=None),
      tf.keras.layers.Embedding(len(unique_user_ids) + 1, embedding_dimension)
    ])

    # Compute embeddings for movies.
    self.movie_embeddings = tf.keras.Sequential([
      tf.keras.layers.StringLookup(
        vocabulary=unique_movie_titles, mask_token=None),
      tf.keras.layers.Embedding(len(unique_movie_titles) + 1, embedding_dimension)
    ])

    # Compute predictions.
    self.ratings = tf.keras.Sequential([
      # Learn multiple dense layers.
      tf.keras.layers.Dense(256, activation="relu"),
      tf.keras.layers.Dense(64, activation="relu"),
      # Make rating predictions in the final layer.
      tf.keras.layers.Dense(1)
  ])
    
  def call(self, inputs):

    user_id, movie_title = inputs

    user_embedding = self.user_embeddings(user_id)
    movie_embedding = self.movie_embeddings(movie_title)

    return self.ratings(tf.concat([user_embedding, movie_embedding], axis=1))

In [ ]:
task = tfrs.tasks.Ranking(
  loss = tf.keras.losses.MeanSquaredError(),
  metrics=[tf.keras.metrics.RootMeanSquaredError()]
)

In [ ]:
class MovielensModel(tfrs.models.Model):

  def __init__(self):
    super().__init__()
    self.ranking_model: tf.keras.Model = RankingModel()
    self.task: tf.keras.layers.Layer = tfrs.tasks.Ranking(
      loss = tf.keras.losses.MeanSquaredError(),
      metrics=[tf.keras.metrics.RootMeanSquaredError()]
    )

  def call(self, features: Dict[str, tf.Tensor]) -> tf.Tensor:
    return self.ranking_model(
        (features["user_id"], features["movie_title"]))

  def compute_loss(self, features: Dict[Text, tf.Tensor], training=False) -> tf.Tensor:
    labels = features.pop("user_rating")
    
    rating_predictions = self(features)

    # The task computes the loss and the metrics.
    return self.task(labels=labels, predictions=rating_predictions)

In [ ]:
model = MovielensModel()
model.compile(optimizer=tf.keras.optimizers.Adagrad(learning_rate=0.1))

In [ ]:
cached_train = train.shuffle(100_000).batch(8192).cache()
cached_test = test.batch(4096).cache()

In [ ]:
model.fit(cached_train, epochs=3)

In [ ]:
model.evaluate(cached_test, return_dict=True)